version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: fittrack-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fittrack
      POSTGRES_PASSWORD: fittrack
      POSTGRES_DB: fittrack
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - fittrack-network

volumes:
  postgres_data:

networks:
  fittrack-network:
    driver: bridge