## Registrar Atleta

POST http://localhost:8080/athlete HTTP/1.1
Content-Type: application/json
Host: localhost:8080

{
    "name": "johdoe",
    "email": "thd@exle.com",
    "age": "25",
    "goal": "EMAGRECIMENTO",
    "role": "ATHLETE"
}
