# Registrar Atleta

POST http://localhost:8080/athlete HTTP/1.1
Content-Type: application/json
Host: localhost:8080

{
    "name": "johdoe",
    "email": "thd@exle.com",
    "age": "25",
    "goal": "EMAGRECIMENTO",
    "role": "ATHLETE"
}

###

# Registrar Instrutor
POST http://localhost:8080/coach HTTP/1.1
Content-Type: application/json
Host: localhost:8080

{
    "name": "Mary Doe",
    "username": "themarydoe",
    "email": "theMaryDoe@example.com",
    "password": "123456",
    "role": "COACH"
}

###

# Registrar Ficha de Treino
POST http://localhost:8080/training-sheet HTTP/1.1
Content-Type: application/json
Host: localhost:8080

{
    "name": "Ficha para iniciantes",
    "description": "conjunto de exercícios pensado em quem está nas primeiras semanas de treino",
    "goal": "CONDICIONAMENTO",
    "duration": "3 semanas",
    "createdBy": "JOHN DOE"
}

